# Generated by Django 4.1.3 on 2022-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50, verbose_name='Goal')),
                ('content', models.TextField(max_length=3000, verbose_name='Description')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('deadline', models.DateTimeField(auto_now=True, verbose_name='Deadline')),
            ],
        ),
    ]
