# Generated by Django 4.1.3 on 2022-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_todo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='choice',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=15, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='goal',
            field=models.CharField(max_length=10, verbose_name='Goal'),
        ),
    ]
