# Generated by Django 4.1.3 on 2022-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_todo_choice_alter_todo_content_alter_todo_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='started',
            field=models.DateField(auto_now_add=True, verbose_name='Started'),
        ),
    ]
